name: Scheduled Tasks

on:
  schedule:
    - cron: '59 23 * * 0'  # Run at 23:59 every Sunday
    - cron: '0 0 * * 1'    # Run at 00:00 every Monday

jobs:
  run_scheduled_tasks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run scheduled tasks
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: python app.py
